# Generated by Django 4.0.5 on 2022-07-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUsers',
            new_name='NewUser',
        ),
    ]
