# Generated by Django 4.0.5 on 2022-07-18 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_remove_newuser_email_remove_newuser_fnmame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField()),
                ('message', models.TextField()),
                ('nameCombo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.name_combination')),
            ],
        ),
    ]
