# Generated by Django 4.0.5 on 2022-07-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_name_combination_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='nameCombo',
        ),
        migrations.AddField(
            model_name='message',
            name='combo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Name_combination',
        ),
    ]
