# Generated by Django 4.0.5 on 2022-08-03 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_name_combination_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='nameCombo',
        ),
        migrations.AddField(
            model_name='message',
            name='combo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newuser',
            name='unique_id',
            field=models.CharField(default='nothing', max_length=21),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 18, 5, 24, 63049)),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='firstName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='lastName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userEmail',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userPassword',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Name_combination',
        ),
    ]
