# Generated by Django 4.0.5 on 2022-07-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0005_remove_message_namecombo_message_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='combo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
