# Generated by Django 4.0.5 on 2022-08-03 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0005_remove_message_namecombo_message_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 18, 5, 52, 292111)),
        ),
    ]
