# Generated by Django 4.0.5 on 2022-07-26 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0006_alter_message_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='unique_id',
            field=models.CharField(default=None, max_length=21),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 10, 4, 0, 167700)),
        ),
    ]
