# Generated by Django 4.0.5 on 2022-07-26 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0008_alter_message_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 10, 4, 27, 793027)),
        ),
    ]
