# Generated by Django 4.0.5 on 2022-07-27 17:27

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0012_alter_message_date_and_time_alter_newuser_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.CharField(default=uuid.uuid3, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 22, 57, 2, 37320)),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=21, unique=True),
        ),
    ]
