# Generated by Django 4.0.5 on 2022-07-27 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0013_newuser_status_alter_message_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 22, 57, 18, 41356)),
        ),
    ]
