# Generated by Django 4.0.5 on 2022-07-27 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0014_alter_message_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 23, 1, 54, 51814)),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
