# Generated by Django 4.0.5 on 2022-08-03 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0015_alter_message_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 18, 6, 48, 352769)),
        ),
    ]
