# Generated by Django 4.0.5 on 2022-08-03 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0016_remove_newuser_status_alter_message_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 12, 41, 27, 233373)),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='firstName',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='lastName',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='unique_id',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userEmail',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userPassword',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
