# Generated by Django 4.0.5 on 2022-08-03 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0017_alter_message_date_and_time_alter_newuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 12, 43, 39, 848011)),
        ),
    ]
