# Generated by Django 4.0.5 on 2022-08-03 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0024_alter_message_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 18, 16, 1, 628215)),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userPassword',
            field=models.TextField(max_length=150),
        ),
    ]
